name: Pull Request Opened
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
#  pr-labeler:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: TimonVS/pr-labeler-action@v3
#        with:
#          configuration-path: .github/pr-labeler-config.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
